# Generated by Django 4.2.1 on 2023-05-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('duracion_horas', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='peliculas')),
                ('clasificacion_edad', models.CharField(choices=[('+0', '+0'), ('+7', '+7'), ('+12', '+12'), ('+16', '+16'), ('+18', '+18')], max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('num_filas', models.PositiveIntegerField(default=0)),
                ('num_columnas', models.PositiveIntegerField(default=0)),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='Peliculas.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='Peliculas.pelicula')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='Peliculas.sala')),
            ],
            options={
                'verbose_name': 'sesion',
                'verbose_name_plural': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('num_butaca', models.PositiveIntegerField()),
                ('ocupada', models.BooleanField(default=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butacas', to='Peliculas.sala')),
            ],
            options={
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
