# Generated by Django 4.2.1 on 2023-06-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pelicula',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Peliculas.pelicula'),
            preserve_default=False,
        ),
    ]
