# Generated by Django 4.2.1 on 2023-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0003_reserva_pelicula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butaca',
            old_name='numero',
            new_name='columna',
        ),
        migrations.AlterUniqueTogether(
            name='butaca',
            unique_together={('sala', 'fila', 'columna')},
        ),
    ]
