# Generated by Django 4.2.1 on 2023-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0005_remove_reserva_columna_remove_reserva_fila_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Peliculas.pelicula'),
        ),
    ]
