# Generated by Django 4.2.1 on 2023-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0006_alter_reserva_pelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
